#!/bin/bash

set -e

JAILHOUSE=jailhouse
LOADER=linux-loader.bin
KERN_ADDR=0x80000000
DTB_ADDR=0x81400000
INITRD_ADDR=0x82000000

ETC_JH=/etc/jailhouse
NONROOT_INITRD=/root/rootfs.cpio.gz

PLIC="plic"
if [ -d /proc/device-tree/soc/aplic@c000000/ ]; then
	PLIC="aplic"
fi

IMSIC=""
if [ -d /proc/device-tree/soc/imsics@28000000/ ]; then
	IMSIC="-imsic"
fi

# Check whether we're on the NOEL-V target, or in a QEMU VM
SYS=$(cat /proc/device-tree/compatible)
if [ $SYS == "riscv-virtio" ]; then
	SYS="qemu"
	CELL=$ETC_JH/qemu-linux-demo-${PLIC}${IMSIC}.cell
	DTB=$ETC_JH/qemu-linux-inmate-${PLIC}${IMSIC}.dtb
else
	SYS="noelv"
	CELL=$ETC_JH/noelv-linux-demo.cell
	DTB=$ETC_JH/noelv-linux-inmate.dtb
fi

CONFIG=$ETC_JH/$SYS
# If more than one CPU exist, take the MC config
if [[ -d "/sys/devices/system/cpu/cpu1" ]]; then
	CONFIG="${CONFIG}-${PLIC}${IMSIC}-mc.cell"
else
	CONFIG="${CONFIG}-${PLIC}${IMSIC}-uc.cell"
fi
