#!/bin/bash

set -e

JAILHOUSE=jailhouse
LOADER=linux-loader.bin
KERN_ADDR=0x80000000
DTB_ADDR=0x81400000
INITRD_ADDR=0x82000000

ETC_JH=/etc/jailhouse
NONROOT_INITRD=/root/rootfs.cpio.gz

PLIC="plic"
IMSIC=""

# Check whether we're on the NOEL-V target, or in a QEMU VM
SYS=$(cat /proc/device-tree/compatible)
if [ $SYS == "riscv-virtio" ]; then
	if [ -d /proc/device-tree/soc/interrupt-controller@c000000/ ]; then
		PLIC="aplic"
	fi
	if [ -d /proc/device-tree/soc/interrupt-controller@28000000/ ]; then
		IMSIC="-imsic"
	fi

	SYS="qemu"
	LINUX_CELL=$ETC_JH/qemu-linux-demo-${PLIC}${IMSIC}.cell
	LINUX_DTB=$ETC_JH/qemu-linux-inmate-${PLIC}${IMSIC}.dtb
	TINY_CELL=$ETC_JH/qemu-inmate-demo.cell
	TINY_INMATE=$ETC_JH/timer-demo.bin
elif [ $SYS == "lfd,vcu118-rocket" ]; then
	SYS="vcu118-rocket"
else
	echo "Unknown platform"
	exit 1
fi

CONFIG=$ETC_JH/$SYS
# If more than one CPU exist, take the MC config
if [[ -d "/sys/devices/system/cpu/cpu1" ]]; then
	CONFIG="${CONFIG}-${PLIC}${IMSIC}-mc.cell"
else
	CONFIG="${CONFIG}-${PLIC}${IMSIC}-uc.cell"
fi
