#!/bin/bash

set -e

source jh-env

KERNEL=/root/Image
#KERNEL=/root/grinch.bin

CELL_NAME="linux-demo"

echo "Using config $CELL DTS: $LINUX_DTB"

if [[ -d "/sys/devices/system/cpu/cpu1" ]]; then
	$JAILHOUSE cell create $LINUX_CELL
	$JAILHOUSE cell load $CELL_NAME \
		/etc/jailhouse/$LOADER -a 0 \
		-s "kernel=$KERN_ADDR dtb=$DTB_ADDR" -a 0x100 \
		$KERNEL -a $KERN_ADDR \
		$LINUX_DTB -a $DTB_ADDR \
		$NONROOT_INITRD -a $INITRD_ADDR
	$JAILHOUSE cell start $CELL_NAME
fi
