#! /bin/sh

/bin/mount -a

mkdir -p /dev
/bin/mount -t devtmpfs devtmpfs /dev
/sbin/insmod /jailhouse.ko


mkdir -p /dev/pts
/bin/mount -t devpts devpts /dev/pts
telnetd -l /bin/bash

cd /sys/module/jailhouse/sections/
echo $(cat .text) " -s .bss " $(cat .bss) " -s .data " $(cat .data)
